### ISSUE TITLE
ActivityManager forces activity shutdown

### ISSUE THREAD

**Issue by arbitrary-dev** [arbitrary-dev/kanji#22]
From time to time. Perhaps can be reproduced with many kanji's and loading delays.

**Comment by arbitrary-dev** [comment]
~~You know, `Cache.onUpdate()` is actually called from a different thread rather than UI one!~~
No, it's not true.

**Comment by arbitrary-dev** [comment]
Probably race conditions when loading many kanji's.
Try a string with single kanji followed by many hiragana or katakana. Cache should be empty!

**Comment by arbitrary-dev** [comment]
Certainly a race condition!

Sometimes info for the next kanji gets loaded in current fragment, then gets overwritten by actual info and swiping to next kanji results in "null" info.

Maybe `DataTask`'s got misused and concurrently update `WebView`?

**Comment by arbitrary-dev** [comment]
Maybe `Activity` associated with `PagerAdapter` no longer exist?
```
07-20 23:02:23.591 D/AndroidRuntime: Shutting down VM
07-20 23:02:23.591 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.gay.kanji, PID: 25453
    java.lang.IllegalStateException: Activity has been destroyed
        at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1515)
        at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:638)
        at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:621)
        at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:162)
        at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:1003)
        at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:2996)
        at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:279)
        at com.example.gay.kanji.KanjiActivity.lambda$resetPager$1$KanjiActivity(KanjiActivity.java:97)
        at com.example.gay.kanji.KanjiActivity$$Lambda$1.onCacheUpdated(Unknown Source)
        at com.example.gay.kanji.data.Cache.onUpdate(Cache.java:37)
        at com.example.gay.kanji.data.Cache.put(Cache.java:21)
        at com.example.gay.kanji.data.DataRetriever.lambda$update$0$DataRetriever(DataRetriever.java:78)
        at com.example.gay.kanji.data.DataRetriever$$Lambda$0.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7229)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
```
